### PR TITLE
REST Capability, Tests

### PR DESCRIPTION
**Pull request by jerinphilip**
soundex/**init**.py ->
    Required functions for WSME REST

soundex/tests/test_soundex.py ->
    Tests for the above functions

### CODE REVIEW

**Comment by jerinphilip** [comment]
@copyninja Will these tests do, they aren't much different from the given ones for the original soundex. I'm a little confused as to how to add tests for the REST Service testing.

**Comment by copyninja** [comment]
For now these tests should be fine. But it should be possible to write test to invoke the functions exposing functionality with JSON input as in case of REST. If you have time constraint lets postpone it to post Gsoc time.

**Comment by copyninja** [comment]
Also are you sure if expose_ functions really do work by using it with Flask front end.

**Comment by jerinphilip** [comment]
@copyninja:
app.py inside [jerinphilip/ported] (https://github.com/jerinphilip/ported) is where I'm tracking. Currently I'm testing with the python3 snippet in your blog. Added an additional GET to check from browser.

**Pull request merged**
