### PR TITLE
Issue#9 Resolved.

### PR DESCRIPTION
**Pull request by arushidogra**
Issue#9 regarding incorrect results is now resolved.
screenshot from 2016-03-08 15 55 34
screenshot from 2016-03-08 15 55 47
screenshot from 2016-03-08 15 56 00

### CODE REVIEW

**Comment by arushidogra** [comment]
@copyninja  , can you look into this?

**Comment by arushidogra** [comment]
@copyninja

**Comment by copyninja** [comment]
Why did you close this issue?. You don't want this to be merged?

**Comment by arushidogra** [comment]
@copyninja , that was a mistake. Sorry for the confusion. I reopened it. Can you look through the changes?

**Comment by copyninja** [comment]
@arushidogra Can you base this PR on development branch?. Development branch has the /api part already fixed. I've force pushed changes since I had messed up repository a bit. So you might get conflict in which case please clone fresh

**Pull request closed without merging**
